package com.jpd.shop.cashier.source;

import java.awt.Font;

import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;

import com.jpd.shop.common_files.Colors;
import com.jpd.shop.common_files.MainFrame;

/**
 *
 * @author jpd
 */
public class PaymentDialog extends javax.swing.JDialog {

    public static void main(String[] args) {
        showDialog(100.0f);
    }

    public static void showDialog(float totalPrice) {
        new PaymentDialog(totalPrice);
    }

    private final Font[] FONT = {
            new Font("Segoe UI", 0, 24),
            new Font("Segoe UI", 0, 14)
    };

    private final float TOTAL_PRICE;

    private PaymentDialog(float totalPrice) {
        super(MainFrame.getInstance(), true);

        TOTAL_PRICE = totalPrice;

        this.setUndecorated(true);
        this.initComponents();
        this.setLocationRelativeTo(MainFrame.getInstance());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        bayad = new javax.swing.JSpinner();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        javax.swing.JButton orderButton = new javax.swing.JButton();
        javax.swing.JButton editButton = new javax.swing.JButton();
        kulangTimKwarta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(FONT[0]);
        jLabel1.setText("Cash:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 70, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(FONT[0]);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(Double.toString(TOTAL_PRICE));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 40, 250, 60);

        jLabel3.setBackground(getBackground());
        jLabel3.setFont(FONT[0]);
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 40, 70, 60);

        bayad.setFont(FONT[0]);
        bayad.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.25f));
        bayad.setBorder(null);
        getContentPane().add(bayad);
        bayad.setBounds(110, 120, 250, 60);

        cancelButton.setFont(FONT[1]);
        cancelButton.setText("CANCEL");
        cancelButton.setCursor(MainFrame.HAND_CURSOR);
        cancelButton.setFocusable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(265, 210, 90, 60);

        orderButton.setFont(FONT[1]);
        orderButton.setText("ORDER");
        orderButton.setCursor(MainFrame.HAND_CURSOR);
        orderButton.setFocusable(false);
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(orderButton);
        orderButton.setBounds(30, 210, 90, 60);

        editButton.setFont(FONT[1]);
        editButton.setText("EDIT");
        editButton.setCursor(MainFrame.HAND_CURSOR);
        editButton.setFocusable(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton);
        editButton.setBounds(145, 210, 90, 60);

        kulangTimKwarta.setForeground(Colors.RED);
        kulangTimKwarta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        kulangTimKwarta.setText("cash is less than the total price");
        kulangTimKwarta.setVisible(false);
        getContentPane().add(kulangTimKwarta);
        kulangTimKwarta.setBounds(30, 10, 330, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_orderButtonActionPerformed

        if (TOTAL_PRICE > (float) bayad.getValue()) {
            kulangTimKwarta.setVisible(true);
            return;
        }

        // TODO add your handling code here:

        this.dispose();
    }// GEN-LAST:event_orderButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_editButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        ProductsPanel.getInstance().TRAY_PRODUCTS_CONTAINER.removeAll();
        this.dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bayad;
    private javax.swing.JLabel kulangTimKwarta;
    // End of variables declaration//GEN-END:variables
}
