/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jpd.shop.cashier.source;

import javax.swing.ImageIcon;

import com.jpd.shop.common_files.Colors;
import com.jpd.shop.common_files.ProductCard.ProductCard;
import com.jpd.shop.common_files.data_types.ProductData;
import java.awt.Graphics;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;

/**
 *
 * @author jpd
 */
public class TrayProductCard extends javax.swing.JPanel {

    private static TrayProductCard selectedCard = null;

    public static final void changeSelectedCard(TrayProductCard newSelectedCard) {
        if (selectedCard != null) {
            changeSelectedCardColor(false);
        }

        selectedCard = newSelectedCard;

        changeSelectedCardColor(true);
    }

    public static final TrayProductCard getSelectedCard() {
        return selectedCard;
    }

    private static void changeSelectedCardColor(boolean isSelected) {
        if (selectedCard == null) {
            return;
        }

        selectedCard.NAME.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);
        selectedCard.PRICE_LABEL.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);
        selectedCard.PRICE.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);
        selectedCard.QUANTITY_LABEL.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);
        selectedCard.QUANTITY.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);

        selectedCard.setBackground(isSelected
                ? Colors.BLUE
                : Colors.WHITE);
    }

    private final ProductData PRODUCT_DATA;
    private final int RADIUS = 18;
    private Shape shape;

    public TrayProductCard() {
        PRODUCT_DATA = new ProductData("adfghjkl kjhgfdsdfghjklk jhgfdfghjklkjhg dfghjklnbmjhfdcvbjgf", 0, 0, 1,
                new byte[1], 1);
        initComponents();
    } // TODO: tanggala ini

    public TrayProductCard(ProductData productData) {
        PRODUCT_DATA = productData;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(getBackground());
        g.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
        super.paintComponent(g);
    }

    @Override
    protected void paintBorder(Graphics g) {
        g.setColor(getForeground());
        g.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
    }

    @Override
    public boolean contains(int x, int y) {
        if (shape == null || !shape.getBounds().equals(getBounds())) {
            shape = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
        }
        return shape.contains(x, y);
    }

    public void changeQuantity(int quantity) {
        QUANTITY.setText(Integer.toString(quantity));
    }

    private String getProductName() {
        return ("<html><body style:'width: " + IMAGE.getWidth() + "px'><p>"
                + PRODUCT_DATA.name() + "</p></body></html>");
    }

    private String getProductPrice() {
        return Float.toString(PRODUCT_DATA.price() / 100.f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMAGE = new javax.swing.JLabel(new ImageIcon(PRODUCT_DATA.image()));
        NAME = new javax.swing.JLabel();
        PRICE_LABEL = new javax.swing.JLabel();
        QUANTITY_LABEL = new javax.swing.JLabel();
        PRICE = new javax.swing.JLabel(getProductPrice());
        QUANTITY = new javax.swing.JLabel();

        setBackground(Colors.WHITE);
        setMaximumSize(new java.awt.Dimension(240, 120));
        setMinimumSize(new java.awt.Dimension(240, 120));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(240, 120));
        setLayout(null);

        IMAGE.setBackground(new java.awt.Color(204, 255, 255));
        IMAGE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMAGE.setMaximumSize(new java.awt.Dimension(100, 100));
        IMAGE.setMinimumSize(new java.awt.Dimension(100, 100));
        IMAGE.setPreferredSize(new java.awt.Dimension(100, 100));
        add(IMAGE);
        IMAGE.setBounds(10, 10, 100, 100);

        NAME.setBackground(new java.awt.Color(204, 255, 255));
        NAME.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NAME.setMaximumSize(new java.awt.Dimension(110, 40));
        NAME.setMinimumSize(new java.awt.Dimension(110, 40));
        NAME.setPreferredSize(new java.awt.Dimension(110, 40));
        NAME.setText(getProductName());
        add(NAME);
        NAME.setBounds(120, 10, 110, 50);

        PRICE_LABEL.setText("Price:");
        add(PRICE_LABEL);
        PRICE_LABEL.setBounds(120, 60, 50, 20);

        QUANTITY_LABEL.setText("Quantity:");
        add(QUANTITY_LABEL);
        QUANTITY_LABEL.setBounds(120, 90, 60, 20);

        PRICE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(PRICE);
        PRICE.setBounds(170, 60, 60, 20);

        QUANTITY.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        QUANTITY.setText("0");
        add(QUANTITY);
        QUANTITY.setBounds(170, 90, 60, 20);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGE;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PRICE;
    private javax.swing.JLabel PRICE_LABEL;
    private javax.swing.JLabel QUANTITY;
    private javax.swing.JLabel QUANTITY_LABEL;
    // End of variables declaration//GEN-END:variables
}
