package com.jpd.shop.cashier.source.resibo;

import com.jpd.shop.cashier.source.TrayProductCard;

public class ProductResiboTemplate extends javax.swing.JPanel {

    private final TrayProductCard TRAY_PRODUCT_CARD;

    ProductResiboTemplate(TrayProductCard card) {
        TRAY_PRODUCT_CARD = card;
        initComponents();
        this.setVisible(true);
    }

    private float getSubTotal() {
        String priceString = price.getText();
        float price = Float.parseFloat(priceString);
        int qty = Integer.parseInt(quantity.getText());

        return price * qty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 26));
        setLayout(null);

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setText(TRAY_PRODUCT_CARD.PRODUCT_DATA.name());
        add(name);
        name.setBounds(10, 0, 140, 20);

        price.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        price.setText(Float.toString(TRAY_PRODUCT_CARD.PRODUCT_DATA.price() / 100.f));
        add(price);
        price.setBounds(160, 0, 60, 20);

        quantity.setText(Integer.toString(TRAY_PRODUCT_CARD.getQuantity(true)));
        add(quantity);
        quantity.setBounds(250, 0, 30, 20);

        jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel.setText("*");
        add(jlabel);
        jlabel.setBounds(220, 0, 20, 20);

        subTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotal.setText(Float.toString(getSubTotal()));
        add(subTotal);
        subTotal.setBounds(310, 0, 50, 20);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel subTotal;
    // End of variables declaration//GEN-END:variables
}
