/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jpd.shop.common_files.ProductCard;

import com.jpd.shop.common_files.Colors;
import com.jpd.shop.common_files.MainFrame;
import com.jpd.shop.common_files.data_types.ProductData;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

import javax.swing.JLabel;

/**
 *
 * @author jpd
 */
public class ProductCard extends javax.swing.JPanel {

    private static ProductCard selectedCard = null;

    public static final void changeSelectedCard(ProductCard newSelectedCard) {
        if (selectedCard != null) {
            changeSelectedCardColor(false);
        }

        selectedCard = newSelectedCard;

        changeSelectedCardColor(true);
    }

    public static final ProductCard getSelectedCard() {
        return selectedCard;
    }

    private static void changeSelectedCardColor(boolean isSelected) {
        if (selectedCard == null) {
            return;
        }

        JLabel[] labels = {
                selectedCard.productCardTemplate1.getProductNameLabel(),
                selectedCard.productCardTemplate1.getPriceLabel(),
                selectedCard.productCardTemplate1.getRealPriceLabel(),
                selectedCard.productCardTemplate1.getStockLabel(),
                selectedCard.productCardTemplate1.getRealStockLabel()
        };

        for (JLabel label : labels) {
            label.setForeground(isSelected ? Colors.WHITE : Colors.BLACK);
        }

        selectedCard.layerdPane.setBackground(isSelected
                ? Colors.BLUE
                : Colors.WHITE);
    }

    public final ProductData PRODUCT_DATA;
    private final int RADIUS = 18;
    private Shape shape;

    public ProductCard(ProductData productData) {
        PRODUCT_DATA = productData;

        initComponents();

        this.setOpaque(false);
    }

    public ProductCardTemplate getProductCardTemplate() {
        return productCardTemplate1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated
    //
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc=" Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerdPane = new javax.swing.JLayeredPane() {
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(getBackground());
                g.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
                super.paintComponent(g);
            }

            @Override
            protected void paintBorder(Graphics g) {
                g.setColor(getForeground());
                g.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
            }

            @Override
            public boolean contains(int x, int y) {
                if (shape == null || !shape.getBounds().equals(getBounds())) {
                    shape = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, RADIUS, RADIUS);
                }
                return shape.contains(x, y);
            }
        };
        productCardTemplate1 = new com.jpd.shop.common_files.ProductCard.ProductCardTemplate(PRODUCT_DATA);
        productNotAvailable = new javax.swing.JPanel();

        setForeground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(150, 225));
        setMinimumSize(new java.awt.Dimension(150, 225));
        setPreferredSize(new java.awt.Dimension(150, 225));

        layerdPane.setBackground(Colors.WHITE);
        layerdPane.setMaximumSize(new java.awt.Dimension(150, 225));
        layerdPane.setMinimumSize(new java.awt.Dimension(150, 225));
        layerdPane.setOpaque(false);
        layerdPane.setPreferredSize(new java.awt.Dimension(150, 225));

        productCardTemplate1.setMaximumSize(new java.awt.Dimension(150, 225));
        productCardTemplate1.setMinimumSize(new java.awt.Dimension(150, 225));
        productCardTemplate1.setOpaque(false);
        productCardTemplate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                productCardMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout productCardTemplate1Layout = new javax.swing.GroupLayout(productCardTemplate1);
        productCardTemplate1.setLayout(productCardTemplate1Layout);
        productCardTemplate1Layout.setHorizontalGroup(
                productCardTemplate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE));
        productCardTemplate1Layout.setVerticalGroup(
                productCardTemplate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 225, Short.MAX_VALUE));

        layerdPane.add(productCardTemplate1);
        productCardTemplate1.setBounds(0, 0, 150, 225);

        productNotAvailable.setMaximumSize(new java.awt.Dimension(150, 225));
        productNotAvailable.setMinimumSize(new java.awt.Dimension(150, 225));
        productNotAvailable.setOpaque(false);
        productNotAvailable.setPreferredSize(new java.awt.Dimension(150, 225));
        productNotAvailable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consumeMouseEventsForProductNotAvailablePanel(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consumeMouseEventsForProductNotAvailablePanel(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                consumeMouseEventsForProductNotAvailablePanel(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                consumeMouseEventsForProductNotAvailablePanel(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                consumeMouseEventsForProductNotAvailablePanel(evt);
            }
        });

        javax.swing.GroupLayout productNotAvailableLayout = new javax.swing.GroupLayout(productNotAvailable);
        productNotAvailable.setLayout(productNotAvailableLayout);
        productNotAvailableLayout.setHorizontalGroup(
                productNotAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE));
        productNotAvailableLayout.setVerticalGroup(
                productNotAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 225, Short.MAX_VALUE));

        JLabel notAvailableText = new JLabel("Not Available");
        notAvailableText.setForeground(Colors.WHITE);
        notAvailableText.setHorizontalAlignment(JLabel.CENTER);
        notAvailableText.setVisible(true);

        productNotAvailable.setLayout(new BorderLayout());
        productNotAvailable.add(notAvailableText, BorderLayout.CENTER);
        productNotAvailable.setBounds(0, 0, 150, 200);
        productNotAvailable.setOpaque(false);
        productNotAvailable.setVisible(true);
        layerdPane.setLayer(productNotAvailable, javax.swing.JLayeredPane.MODAL_LAYER);
        layerdPane.add(productNotAvailable);
        productNotAvailable.setBounds(0, 0, 150, 225);
        productNotAvailable.setVisible(!(MainFrame.getInstance().IS_ADMIN_APP || PRODUCT_DATA.stock() > 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(layerdPane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(layerdPane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
    }// </editor-fold>//GEN-END:initComponents

    private void consumeMouseEventsForProductNotAvailablePanel(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_consumeMouseEventsForProductNotAvailablePanel
        evt.consume();
    }// GEN-LAST:event_consumeMouseEventsForProductNotAvailablePanel

    private void productCardMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_productCardMouseReleased
        cardClicked();
    }// GEN-LAST:event_productCardMouseReleased

    protected void cardClicked() {
        changeSelectedCard(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layerdPane;
    private com.jpd.shop.common_files.ProductCard.ProductCardTemplate productCardTemplate1;
    private javax.swing.JPanel productNotAvailable;
    // End of variables declaration//GEN-END:variables
}
