package com.jpd.shop.admin.source;

import com.jpd.shop.common_files.MainFrame;
import com.jpd.shop.common_files.data_types.Client;
import com.jpd.shop.common_files.data_types.EmployeeLoginInfo;

public class EmployeeInfoDialog extends javax.swing.JDialog {

    public static void showDialog(EmployeeLoginInfo employeeLoginInfo) {
        new EmployeeInfoDialog(employeeLoginInfo);
    }

    private final EmployeeLoginInfo EMPLOYEE_LOGIN_INFO;

    /**
     * Creates new form EditEmployeeInfo
     */
    private EmployeeInfoDialog(EmployeeLoginInfo employeeLoginInfo) {
        super(MainFrame.getInstance(), true);

        EMPLOYEE_LOGIN_INFO = employeeLoginInfo;

        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        employeeTypeComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 336));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(330, 357));
        getContentPane().setLayout(null);

        jLabel1.setText("Username:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 70, 25);

        usernameField.setText(EMPLOYEE_LOGIN_INFO == null ? "" : EMPLOYEE_LOGIN_INFO.username());
        usernameField.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(usernameField);
        usernameField.setBounds(30, 50, 270, 25);

        jLabel2.setText("Password");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 80, 25);

        passwordField.setText(EMPLOYEE_LOGIN_INFO == null ? "" : EMPLOYEE_LOGIN_INFO.password());
        passwordField.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(passwordField);
        passwordField.setBounds(30, 120, 270, 25);

        jLabel4.setText("Employee Type:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 130, 25);

        employeeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(EmployeeLoginInfo.TYPES_OF_EMPLOYEE));
        employeeTypeComboBox.setPreferredSize(new java.awt.Dimension(200, 25));
        if(EMPLOYEE_LOGIN_INFO != null){
            employeeTypeComboBox.setSelectedItem(
                EMPLOYEE_LOGIN_INFO.type());
        }
        getContentPane().add(employeeTypeComboBox);
        employeeTypeComboBox.setBounds(30, 190, 270, 25);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(170, 250, 130, 50);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(30, 250, 120, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
        if (employeeTypeComboBox.getSelectedIndex() == 0) {
            return;
        }

        EmployeeLoginInfo employeeLoginInfo = new EmployeeLoginInfo(
                EMPLOYEE_LOGIN_INFO == null
                        ? EmployeeLoginInfo.NO_ID_YET
                        : EMPLOYEE_LOGIN_INFO.id(),
                (String) employeeTypeComboBox.getSelectedItem(),
                usernameField.getText(),
                passwordField.getText());

        Client.getInstance().makeARequestToServer(employeeLoginInfo);
        EmployeesInfoPanel.getInstance().loadEmployees();
        dispose();
    }// GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> employeeTypeComboBox;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
