package com.jpd.shop.admin.source;

import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

import com.jpd.shop.common_files.data_types.Client;
import com.jpd.shop.common_files.data_types.EmployeeLoginInfo;
import com.jpd.shop.common_files.data_types.JpdTableModel;
import com.jpd.shop.common_files.data_types.MyPanel_Interface;

/**
 *
 * @author jpd
 */
public class EmployeesInfoPanel extends javax.swing.JPanel implements MyPanel_Interface {

    private static EmployeesInfoPanel employeesInfoPanel;

    public static EmployeesInfoPanel getInstance() {
        if (employeesInfoPanel == null) {
            employeesInfoPanel = new EmployeesInfoPanel();
        }

        return employeesInfoPanel;
    }

    private static final String[] COLUMN_NAMES = {
            "ID", "EMPLOYEE TYPE", "USER NAME", "PASSWORD" };

    private Object[][] tableData;

    private EmployeesInfoPanel() {
        initComponents();

        TABLE.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        loadEmployees();
        this.setVisible(true);
    }

    @Override
    public void disposePanel() {
        employeesInfoPanel = null;
        System.gc();
    }

    void loadEmployees() {
        tableData = (Object[][]) Client.getInstance()
                .makeARequestToServer(Client.GET_LIST_OF_EMPLOYEES);

        TABLE.setModel(new JpdTableModel(tableData, COLUMN_NAMES));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 530));
        setMinimumSize(new java.awt.Dimension(1000, 530));
        setLayout(null);

        jScrollPane1.setViewportView(TABLE);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 1000, 460);

        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(730, 20, 75, 30);

        deleteButton.setText("Delete");
        deleteButton.setFocusable(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
        deleteButton.setBounds(910, 20, 75, 30);

        editButton.setText("Edit");
        editButton.setFocusable(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton);
        editButton.setBounds(820, 20, 75, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed

        if (TABLE.getSelectedRow() == -1) {
            return;
        }

        Client.getInstance().makeARequestToServer(new EmployeeLoginInfo(
                (int) tableData[TABLE.getSelectedRow()][0], "Delete", null, null));
        loadEmployees();
    }// GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        EmployeeInfoDialog.showDialog(null);
    }// GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        int selectedRow = TABLE.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }

        EmployeeInfoDialog.showDialog(new EmployeeLoginInfo(
                (int) tableData[selectedRow][0],
                (String) tableData[selectedRow][1],
                (String) tableData[selectedRow][2],
                (String) tableData[selectedRow][3]));

    }// GEN-LAST:event_editButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JTable TABLE = new javax.swing.JTable();
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
