package com.jpd.shop.admin.source;

import com.jpd.shop.admin.AdminEntryPoint;
import com.jpd.shop.common_files.Colors;
import com.jpd.shop.common_files.MainFrame;
import com.jpd.shop.common_files.MainPanel_Interface;

/**
 *
 * @author jpd
 */
public class MainPanel extends javax.swing.JPanel implements MainPanel_Interface {

    private MainFrame mainFrameRef;

    public MainPanel() {
        initComponents();
        customInit();
    }

    private void customInit() {
        this.setBounds(0, 0, 1000, 580);
        this.setVisible(true);
    }

    @Override
    public void instantiateComponents(boolean instantiate) {
        // TODO: add code
    }

    @Override
    public void setMainFrameRef(MainFrame mainFrameRef) {
        this.mainFrameRef = mainFrameRef;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBar = new javax.swing.JPanel();
        logoutButton = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setPreferredSize(new java.awt.Dimension(1000, 580));
        setLayout(null);

        navBar.setBackground(Colors.GRAY);
        navBar.setPreferredSize(new java.awt.Dimension(1000, 50));
        navBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        logoutButton.setBackground(navBar.getBackground());
        logoutButton.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/jpd/shop/common_files/icons/logout.png"))); // NOI18N
        logoutButton.setToolTipText("");
        logoutButton.setOpaque(true);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutButtonMouseReleased(evt);
            }
        });
        navBar.add(logoutButton);

        add(navBar);
        navBar.setBounds(0, 530, 1000, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutButtonMouseReleased
        mainFrameRef.getLoginPanel().setVisible(true);
    }// GEN-LAST:event_logoutButtonMouseReleased

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setBackground(navBar.getBackground());
    }// GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setBackground(Colors.WHITE_HOVER);
    }// GEN-LAST:event_logoutButtonMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPanel navBar;
    // End of variables declaration//GEN-END:variables

}
