package com.jpd.shop.admin;

import javax.swing.ImageIcon;

/**
 *
 * @author jpd
 */
public class MainFrame extends javax.swing.JFrame {

    private final ImageIcon closeIcon = new ImageIcon(getClass().getResource(
            "/com/jpd/shop/admin/icons/close_button.png"));
    private final ImageIcon redCloseIcon = new ImageIcon(getClass().getResource(
            "/com/jpd/shop/admin/icons/red_close_button.png"));

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionButtonContainer = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        mainPanel1 = new com.jpd.shop.admin.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0,
            this.getWidth(), this.getHeight(), 20, 20));
    setSize(new java.awt.Dimension(1000, 600));
    getContentPane().setLayout(null);

    connectionButtonContainer.setBackground(Colors.GRAY);
    connectionButtonContainer.setMaximumSize(new java.awt.Dimension(1000, 20));
    connectionButtonContainer.setMinimumSize(new java.awt.Dimension(1000, 20));
    connectionButtonContainer.setPreferredSize(new java.awt.Dimension(1000, 20));
    connectionButtonContainer.setLayout(null);

    closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jpd/shop/admin/icons/close_button.png"))); // NOI18N
    closeButton.setMaximumSize(new java.awt.Dimension(20, 20));
    closeButton.setMinimumSize(new java.awt.Dimension(20, 20));
    closeButton.setPreferredSize(new java.awt.Dimension(20, 20));
    closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            closeButtonMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            closeButtonMouseExited(evt);
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            closeButtonMouseReleased(evt);
        }
    });
    connectionButtonContainer.add(closeButton);
    closeButton.setBounds(960, 0, 20, 20);

    getContentPane().add(connectionButtonContainer);
    connectionButtonContainer.setBounds(0, 0, 1000, 20);
    getContentPane().add(mainPanel1);
    mainPanel1.setBounds(0, 20, 1000, 580);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeButtonMouseReleased
        System.exit(0);
    }// GEN-LAST:event_closeButtonMouseReleased

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeButtonMouseExited
        closeButton.setIcon(closeIcon);
    }// GEN-LAST:event_closeButtonMouseExited

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setIcon(redCloseIcon);
    }// GEN-LAST:event_closeButtonMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel connectionButtonContainer;
    private com.jpd.shop.admin.MainPanel mainPanel1;
    // End of variables declaration//GEN-END:variables
}
