/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jpd.shop.common_files;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JLabel;

/**
 *
 * @author jpd
 */
public class ProductCard extends javax.swing.JPanel {

    private final ProductData PRODUCT_DATA;

    public ProductCard(ProductData productData) {
        PRODUCT_DATA = productData;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        productNotAvailable = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g); // Paint the panel's components and borders

                // Set the color with an alpha value (e.g., 128 for 50% transparency)
                Color semiTransparentColor = new Color(128, 128, 128, 191);
                g.setColor(semiTransparentColor);

                // Fill the panel with the semi-transparent color
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        productCardTemplate1 = new com.jpd.shop.common_files.ProductCardTemplate(PRODUCT_DATA);

        setMaximumSize(new java.awt.Dimension(150, 200));
        setMinimumSize(new java.awt.Dimension(150, 200));

        productNotAvailable.setOpaque(false);

        javax.swing.GroupLayout productNotAvailableLayout = new javax.swing.GroupLayout(productNotAvailable);
        productNotAvailable.setLayout(productNotAvailableLayout);
        productNotAvailableLayout.setHorizontalGroup(
            productNotAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        productNotAvailableLayout.setVerticalGroup(
            productNotAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productCardTemplate1Layout = new javax.swing.GroupLayout(productCardTemplate1);
        productCardTemplate1.setLayout(productCardTemplate1Layout);
        productCardTemplate1Layout.setHorizontalGroup(
            productCardTemplate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        productCardTemplate1Layout.setVerticalGroup(
            productCardTemplate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        JLabel notAvailableText = new JLabel("Not Available");
        notAvailableText.setForeground(Colors.WHITE);
        notAvailableText.setHorizontalAlignment(JLabel.CENTER);
        notAvailableText.setVisible(true);

        productNotAvailable.setLayout(new BorderLayout());
        productNotAvailable.add(notAvailableText, BorderLayout.CENTER);
        productNotAvailable.setSize(getWidth(), getHeight());
        productNotAvailable.setLocation(0, 0);
        productNotAvailable.setOpaque(false);
        productNotAvailable.setVisible(true);
        jLayeredPane1.setLayer(productNotAvailable, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.setLayer(productCardTemplate1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productCardTemplate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(productNotAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productCardTemplate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(productNotAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private com.jpd.shop.common_files.ProductCardTemplate productCardTemplate1;
    private javax.swing.JPanel productNotAvailable;
    // End of variables declaration//GEN-END:variables
}
