/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jpd.shop.common_files;

import java.awt.Dimension;
import java.awt.Image;

import javax.swing.ImageIcon;

/**
 *
 * @author jpd
 */
public class ProductCardTemplate extends javax.swing.JPanel {

    private final ProductData PRODUCT_DATA;

    public ProductCardTemplate() {
        PRODUCT_DATA = null;
    }

    public ProductCardTemplate(ProductData productData) {
        PRODUCT_DATA = productData;

        initComponents();
        customInit();
    }

    private void customInit() {
        Dimension dimension = new Dimension(150, 200);
        this.setPreferredSize(dimension);
        // this.setMaximumSize(dimension);
        // this.setMinimumSize(dimension);
        // this.setBounds(0, 0, 150, 200);
        this.setVisible(true);
    }

    private ImageIcon getProductImage() {
        Image image = new ImageIcon(PRODUCT_DATA.image()).getImage();
        return (new ImageIcon(image.getScaledInstance(
                100, 100, Image.SCALE_SMOOTH)));
    }

    private String getProductName() {
        return ("<html><body style='width: 200px; word-wrap: break-word;'>"
                + PRODUCT_DATA.name() + "</body></html>");
    }

    private String getProductPrice() {
        return Float.toString(PRODUCT_DATA.price() / 100.f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel(getProductImage());
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel(getProductPrice());
        productName = new javax.swing.JLabel(getProductName());

        setMaximumSize(new java.awt.Dimension(150, 200));
        setMinimumSize(new java.awt.Dimension(150, 200));
        setLayout(null);

        image.setBackground(new java.awt.Color(204, 204, 204));
        image.setMaximumSize(new java.awt.Dimension(100, 100));
        image.setMinimumSize(new java.awt.Dimension(100, 100));
        image.setName(""); // NOI18N
        image.setOpaque(true);
        image.setPreferredSize(new java.awt.Dimension(100, 100));
        add(image);
        image.setBounds(25, 10, 100, 100);

        jSeparator1.setMaximumSize(new java.awt.Dimension(150, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(150, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 5));
        add(jSeparator1);
        jSeparator1.setBounds(0, 120, 150, 5);

        jLabel1.setText("Price:");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 15));
        add(jLabel1);
        jLabel1.setBounds(20, 180, 40, 15);

        productPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(productPrice);
        productPrice.setBounds(60, 180, 70, 15);

        productName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        productName.setMaximumSize(new java.awt.Dimension(110, 40));
        productName.setMinimumSize(new java.awt.Dimension(110, 40));
        productName.setPreferredSize(new java.awt.Dimension(110, 40));
        add(productName);
        productName.setBounds(20, 130, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    // End of variables declaration//GEN-END:variables
}
